# Generated by Django 5.0.2 on 2024-04-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
                ('priority', models.CharField(choices=[('MUHIM', 'MUHIM'), ("O'RTACHA", "O'RTACHA"), ('ODDIY', 'ODDIY')], default='ODDIY', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
